/*
 * File: screen_config.h
 *
 * Created on: 29. 12. 2017
 * Author: Denis Colesnicov <eugustus@gmail.com>
 */

#pragma once

#include <Colors.h>

// #define OPERATOR_DELETE


// Button
#define COLOR_BUTTON_BG COLOR_WHITE
#define COLOR_BUTTON_FG COLOR_BROWN
#define COLOR_BUTTON_FR COLOR_GRAY_BLUE
#define COLOR_BUTTON_BG_ACTIVE COLOR_IVORY
#define COLOR_BUTTON_FG_ACTIVE COLOR_BLACK
#define COLOR_BUTTON_FR_ACTIVE COLOR_BLUE

// ScrollableText
#define COLOR_SCROLLBOX_BG COLOR_WHITE
#define COLOR_SCROLLBOX_FG COLOR_BLACK
#define COLOR_SCROLLBOX_FR COLOR_BUTTON_FR

// Toggle
#define COLOR_TOGGLE_BG COLOR_BUTTON_BG
#define COLOR_TOGGLE_FG COLOR_BUTTON_FG
#define COLOR_TOGGLE_FR COLOR_BUTTON_FR
#define COLOR_TOGGLE_BG_ACTIVE COLOR_BUTTON_BG_ACTIVE
#define COLOR_TOGGLE_FG_ACTIVE COLOR_BUTTON_FG_ACTIVE
#define COLOR_TOGGLE_FR_ACTIVE COLOR_BUTTON_FR_ACTIVE
